### ISSUE TITLE
bug in DefaultMap

### ISSUE THREAD

**Issue by 4nds** [AaronMoat/aaronmoat-blog#1]
I found your implementation of DefaultMap in your blog [Implementing Python's defaultdict in JavaScript](https://aaronmoat.com/implementing-pythons-defaultdict-in-javascript/) very useful, but I think I found tiny mistake in your code.
In line 3 of [DefaultMap.js ](https://github.com/AaronMoat/aaronmoat-blog/tree/master/content/blog/implementing-pythons-defaultdict-in-javascript/js/) instead of `super(mapConstructorArgs);` it should be `super(...mapConstructorArgs);`. I assume that constructor of DefaultMap should work the same as [constructor of Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/Map) but with additional first argument `getDefaultValue` . For example, the following code:
`
const d = new DefaultMap(() => '', [
  [1, 'one'],
  [2, 'two'],
  [3, 'three'],
]);
`
should create DefaultMap {1 => 'one', 2 => 'two', 3 => 'three'} with default value of empty string.

**Comment by AaronMoat** [comment]
Good point. Fixed in https://github.com/AaronMoat/aaronmoat-blog/commit/abdae1df6b640d1ab42f475c77e1f86f303fd747. Thanks for the feedback!

(need to get the build working to update the actual page but will do so)
